packages:
  - apps/*
  - fixtures/*/*
  - packages/*

catalog:
  '@next/bundle-analyzer': 16.0.7
  '@next/env': 16.0.7
  '@sanity/client': ^7.13.1
  '@sanity/image-url': ^2.0.1
  '@sanity/preview-url-secret': ^3.0.0
  '@sanity/vision': ^4.19.0
  '@types/node': ^24
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  '@types/react-is': ^19.2.0
  groqd: ^1.7.1
  next: 16.0.7
  react: ^19.2.1
  react-dom: ^19.2.1
  react-is: ^19.2.1
  sanity: ^4.19.0
  styled-components: ^6.1.19
  typescript: 5.9.3

linkWorkspacePackages: deep

overrides:
  '@next/bundle-analyzer': 'catalog:'
  '@next/env': 'catalog:'
  '@types/react': 'catalog:'
  '@types/react-dom': 'catalog:'
  '@types/react-is': 'catalog:'
  next: 'catalog:'
  react: 'catalog:'
  react-dom: 'catalog:'
  react-is: 'catalog:'
  sanity: 'catalog:'
  styled-components: npm:@sanity/styled-components@6.1.23

peerDependencyRules:
  allowAny:
    - react
    - react-dom
    - react-is

preferWorkspacePackages: true

publicHoistPattern:
  - '*prettier*'
