packages:
  - apps/*
  - fixtures/*/*
  - packages/*

catalog:
  '@next/env': 16.2.0-canary.29
  '@sanity/client': ^7.14.1
  '@sanity/image-url': ^2.0.3
  '@sanity/preview-url-secret': ^4.0.3
  '@sanity/tsconfig': ^2.1.0
  '@sanity/vision': 5.8.1
  '@types/node': ^24.10.11
  '@types/react': ^19.2.13
  '@types/react-dom': ^19.2.3
  '@types/react-is': ^19.2.0
  groqd: ^1.7.1
  next: 16.2.0-canary.29
  react: ^19.2.4
  react-dom: ^19.2.4
  react-is: ^19.2.4
  sanity: 5.8.1
  styled-components: ^6.3.8
  typescript: 5.9.3

linkWorkspacePackages: deep

overrides:
  '@next/env': 'catalog:'
  '@types/react': 'catalog:'
  '@types/react-dom': 'catalog:'
  '@types/react-is': 'catalog:'
  next: 'catalog:'
  react: 'catalog:'
  react-dom: 'catalog:'
  react-is: 'catalog:'
  sanity: 'catalog:'
  styled-components: npm:@sanity/styled-components@6.1.23

peerDependencyRules:
  allowAny:
    - react
    - react-dom

preferWorkspacePackages: true
