packages:
  - apps/*
  - fixtures/*/*
  - packages/*

catalog:
  '@next/env': 16.1.1-canary.14
  '@sanity/client': ^7.14.0
  '@sanity/image-url': ^2.0.2
  '@sanity/preview-url-secret': ^4.0.2
  '@sanity/tsconfig': ^2.1.0
  '@sanity/vision': 5.1.0
  '@types/node': ^24.10.4
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  '@types/react-is': ^19.2.0
  groqd: ^1.7.1
  next: 16.1.1-canary.14
  react: ^19.2.3
  react-dom: ^19.2.3
  react-is: ^19.2.3
  sanity: 5.1.0
  styled-components: ^6.2.0
  typescript: 5.9.3

linkWorkspacePackages: deep

overrides:
  '@next/env': 'catalog:'
  '@types/react': 'catalog:'
  '@types/react-dom': 'catalog:'
  '@types/react-is': 'catalog:'
  next: 'catalog:'
  react: 'catalog:'
  react-dom: 'catalog:'
  react-is: 'catalog:'
  sanity: 'catalog:'
  styled-components: npm:@sanity/styled-components@6.1.23

peerDependencyRules:
  allowAny:
    - react
    - react-dom

preferWorkspacePackages: true
