packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  '@next/bundle-analyzer': ^15.3.5
  '@next/env': ^15.3.5
  '@types/react': ^19.1.8
  '@types/react-dom': ^19.1.6
  '@types/react-is': ^19.0.0
  '@sanity/client': ^7.6.0
  '@sanity/image-url': ^1.1.0
  '@sanity/preview-url-secret': ^2.1.12
  '@sanity/ui': ^2.16.7
  '@sanity/vision': ^3.95.0
  groqd: ^0.15.13
  next: ^15.3.5
  react: ^19.1.0
  react-dom: ^19.1.0
  react-is: ^19.1.0
  sanity: ^3.95.0
  styled-components: ^6.1.19
  typescript: 5.8.3