packages:
  - apps/*
  - fixtures/*/*
  - packages/*

catalog:
  '@next/bundle-analyzer': 16.0.1-canary.5
  '@next/env': 16.0.1-canary.5
  '@sanity/client': ^7.12.0
  '@sanity/image-url': ^1.2.0
  '@sanity/preview-url-secret': ^2.1.15
  '@sanity/vision': ^4.6.1
  '@types/node': ^24
  '@types/react': ^19.1.8
  '@types/react-dom': ^19.1.6
  '@types/react-is': ^19.0.0
  groqd: ^1.7.1
  next: 16.0.1-canary.5
  react: ^19.2.0
  react-dom: ^19.2.0
  react-is: ^19.2.0
  sanity: ^4.11.0
  styled-components: ^6.1.19
  typescript: 5.9.3

linkWorkspacePackages: deep

overrides:
  '@next/bundle-analyzer': 'catalog:'
  '@next/env': 'catalog:'
  '@types/react': 'catalog:'
  '@types/react-dom': 'catalog:'
  '@types/react-is': 'catalog:'
  next: 'catalog:'
  react: 'catalog:'
  react-dom: 'catalog:'
  react-is: 'catalog:'
  sanity: 'catalog:'
  styled-components: npm:@sanity/styled-components@6.1.23

peerDependencyRules:
  allowAny:
    - react
    - react-dom
    - react-is

preferWorkspacePackages: true

publicHoistPattern:
  - '*prettier*'
