packages:
  - apps/*
  - fixtures/*/*
  - packages/*

catalog:
  '@next/env': 16.3.0-canary.29
  '@sanity/client': ^7.22.0
  '@sanity/image-url': ^2.1.1
  '@sanity/tsconfig': ^2.1.0
  '@sanity/vision': 5.26.0
  '@types/node': ^24.12.4
  '@types/react': ^19.2.15
  '@types/react-dom': ^19.2.3
  groqd: ^1.7.1
  next: 16.3.0-canary.29
  react: ^19.2.6
  react-dom: ^19.2.6
  sanity: 5.26.0
  styled-components: ^6.4.2
  typescript: 5.9.3

linkWorkspacePackages: deep

overrides:
  '@sanity/client': 'https://pkg.pr.new/sanity-io/client/@sanity/client@619e929'
  '@next/env': 'catalog:'
  '@types/react': 'catalog:'
  '@types/react-dom': 'catalog:'
  next: 'catalog:'
  react: 'catalog:'
  react-dom: 'catalog:'
  sanity: 'catalog:'
  styled-components: npm:@sanity/styled-components@6.1.24

peerDependencyRules:
  allowAny:
    - react
    - react-dom

preferWorkspacePackages: true
