import {imageLoader} from 'next-sanity/image'
import {expect, test} from 'vitest'

test('adds basic width and format parameters', () => {
  const result = imageLoader({
    src: 'https://cdn.sanity.io/images/project/dataset/image.jpg',
    width: 800,
    quality: undefined,
  })

  expect(result).toBe(
    'https://cdn.sanity.io/images/project/dataset/image.jpg?auto=format&fit=max&w=800',
  )
})

test('preserves existing URL parameters', () => {
  const result = imageLoader({
    src: 'https://cdn.sanity.io/images/project/dataset/image.jpg?blur=50',
    width: 800,
    quality: undefined,
  })

  expect(result).toBe(
    'https://cdn.sanity.io/images/project/dataset/image.jpg?blur=50&auto=format&fit=max&w=800',
  )
})

test('adds quality parameter when specified', () => {
  const result = imageLoader({
    src: 'https://cdn.sanity.io/images/project/dataset/image.jpg',
    width: 800,
    quality: 75,
  })

  expect(result).toBe(
    'https://cdn.sanity.io/images/project/dataset/image.jpg?auto=format&fit=max&w=800&q=75',
  )
})

test('uses min fit when height parameter exists', () => {
  const result = imageLoader({
    src: 'https://cdn.sanity.io/images/project/dataset/image.jpg?h=600',
    width: 800,
    quality: undefined,
  })

  expect(result).toBe(
    'https://cdn.sanity.io/images/project/dataset/image.jpg?h=600&auto=format&fit=min&w=800',
  )
})

test('calculates proportional height when both width and height exist', () => {
  const result = imageLoader({
    src: 'https://cdn.sanity.io/images/project/dataset/image.jpg?w=1000&h=500',
    width: 800,
    quality: undefined,
  })

  expect(result).toBe(
    'https://cdn.sanity.io/images/project/dataset/image.jpg?w=800&h=400&auto=format&fit=min',
  )
})

test('respects existing fit parameter', () => {
  const result = imageLoader({
    src: 'https://cdn.sanity.io/images/project/dataset/image.jpg?fit=crop',
    width: 800,
    quality: undefined,
  })

  expect(result).toBe(
    'https://cdn.sanity.io/images/project/dataset/image.jpg?fit=crop&auto=format&w=800',
  )
})

test('handles URLs with hash fragments', () => {
  const result = imageLoader({
    src: 'https://cdn.sanity.io/images/project/dataset/image.jpg#fragment',
    width: 800,
    quality: undefined,
  })

  expect(result).toBe(
    'https://cdn.sanity.io/images/project/dataset/image.jpg?auto=format&fit=max&w=800#fragment',
  )
})

test('handles complex URLs with multiple parameters', () => {
  const result = imageLoader({
    src: 'https://cdn.sanity.io/images/project/dataset/image.jpg?blur=50&sat=-100&w=1000&h=500',
    width: 800,
    quality: 90,
  })

  expect(result).toBe(
    'https://cdn.sanity.io/images/project/dataset/image.jpg?blur=50&sat=-100&w=800&h=400&auto=format&fit=min&q=90',
  )
})

test('rounds the proportional height to the nearest integer', () => {
  const result = imageLoader({
    src: 'https://cdn.sanity.io/images/project/dataset/image.jpg?w=1000&h=333',
    width: 828,
    quality: undefined,
  })

  // 333 / 1000 * 828 = 275.724
  expect(result).toBe(
    'https://cdn.sanity.io/images/project/dataset/image.jpg?w=828&h=276&auto=format&fit=min',
  )
})

test('keeps an existing q parameter when quality is not specified', () => {
  const result = imageLoader({
    src: 'https://cdn.sanity.io/images/project/dataset/image.jpg?q=50',
    width: 800,
    quality: undefined,
  })

  expect(result).toBe(
    'https://cdn.sanity.io/images/project/dataset/image.jpg?q=50&auto=format&fit=max&w=800',
  )
})

test('replaces an existing q parameter when quality is specified', () => {
  const result = imageLoader({
    src: 'https://cdn.sanity.io/images/project/dataset/image.jpg?q=50',
    width: 800,
    quality: 90,
  })

  expect(result).toBe(
    'https://cdn.sanity.io/images/project/dataset/image.jpg?q=90&auto=format&fit=max&w=800',
  )
})

test('forces auto=format even when the URL requests a specific format', () => {
  // `auto=format` lets the CDN negotiate AVIF/WebP based on the Accept
  // header. An explicit `fm` param is preserved, but `auto` always wins on
  // supporting browsers, so `fm` only acts as a fallback format.
  const result = imageLoader({
    src: 'https://cdn.sanity.io/images/project/dataset/image.jpg?auto=compress&fm=png',
    width: 800,
    quality: undefined,
  })

  expect(result).toBe(
    'https://cdn.sanity.io/images/project/dataset/image.jpg?auto=format&fm=png&fit=max&w=800',
  )
})

test('preserves crop and hotspot parameters generated by @sanity/image-url', () => {
  const result = imageLoader({
    src: 'https://cdn.sanity.io/images/project/dataset/image.jpg?rect=40,20,1000,500&fp-x=0.75&fp-y=0.25',
    width: 800,
    quality: undefined,
  })

  // Re-serializing the query percent-encodes the commas in `rect`; the CDN
  // decodes them back so the crop is unaffected
  expect(result).toBe(
    'https://cdn.sanity.io/images/project/dataset/image.jpg?rect=40%2C20%2C1000%2C500&fp-x=0.75&fp-y=0.25&auto=format&fit=max&w=800',
  )
})

test('does not scale the height when only a height parameter is present', () => {
  // Proportional scaling requires both w and h on the URL: with only h the
  // aspect ratio is unknown, so h passes through and fit=min lets the CDN
  // constrain the image to the w x h box without upscaling
  const result = imageLoader({
    src: 'https://cdn.sanity.io/images/project/dataset/image.jpg?h=600',
    width: 1200,
    quality: undefined,
  })

  expect(result).toBe(
    'https://cdn.sanity.io/images/project/dataset/image.jpg?h=600&auto=format&fit=min&w=1200',
  )
})

test('throws a TypeError for relative URLs', () => {
  expect(() =>
    imageLoader({src: '/images/local.jpg', width: 800, quality: undefined}),
  ).toThrowError(TypeError)
})
