name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read # for checkout

jobs:
  release:
    if: github.repository_owner == 'sanity-io'
    runs-on: ubuntu-latest
    permissions:
      contents: read # for checkout
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - uses: actions/create-github-app-token@v3
        id: app-token
        with:
          client-id: ${{ vars.ECOSPARK_CLIENT_ID }}
          private-key: ${{ secrets.ECOSPARK_APP_PRIVATE_KEY }}
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}
          persist-credentials: false
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v7
        with:
          cache: pnpm
          check-latest: true
          node-version: lts/*
      - name: Update npm to use trusted publishing (OIDC)
        run: npm install -g npm@latest
      - run: pnpm install
      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@8488615a623b1b9c987934bb89eae8af6a946ac1 # v2.1.1
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          publish-script: pnpm release
        env:
          NPM_CONFIG_PROVENANCE: ${{ github.event.repository.visibility == 'public' && 'true' || 'false' }}
